on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    # paths: 
    #   - '**/get-github-issue-details.yml'
    #   - '**/github-issues.py'

name: Get GitHub issue details

env:
  # GH_TOKEN: ${{ github.token }}
  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

permissions:
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-issue-json.outputs.json_data }}
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Execute python script
      id: get-issue-json
      run: |
        output=$(python ./.github/scripts/github-issues.py)
        echo "json_data=${output}" >> $GITHUB_OUTPUT

    # - name: Testing python script
    #   run: echo ${{ steps.get-issue-json.outputs.json_data }}

  create:
    needs: build
    if: ${{ needs.build.outputs.matrix != '' && needs.build.outputs.matrix != '{}' && toJSON(fromJSON(needs.build.outputs.matrix)) != '[]' }}
    uses: ./.github/workflows/github-issue-jira-mapping.yml
    strategy:
      matrix: ${{ fromJSON(needs.build.outputs.matrix) }}
      fail-fast: true          
    with:
      project: STP
      github_issue_id: ${{ matrix['details'].id }}
      github_issue_name: ${{ matrix['details'].name }}
      github_issue_url: ${{ matrix['details'].url }}
    secrets: inherit
